### PR TITLE
identical for all environments for now.

### PR DESCRIPTION
**Pull request by Jsyro**
Here is our vc-authn configuration to test logging in to [Business-partner-agents](https://github.com/hyperledger-labs/business-partner-agent).

There will be 1-2 revisions, this is just a first attempt to put the pieces in place.

Let me know if anything looks off.  

Signed-off-by: Jason Sy <jasyrotuck@gmail.com>

### CODE REVIEW

**Comment by esune** [comment]
@Jsyro  we need to know the endpoint for your IdP integration in Keycloak in order to add you to the list of known clients. Let's chat in Rocket.Chat so we can define those as well.


Other than that, the DIDs in the restrictions are the same for all three environments: is this correct? Keep in mind there are three different `vc-authn` instances for `dev/test/prod`: the first two are connected to Sovrin StagingNet, while `prod` is on MainNet.

**Comment by Jsyro** [comment]
@esune I'll provide you those details on RocketChat. 

We don't have a plan for prod, i'm happy to remove that completely if that's ok. 

Same restrictions for Dev and Test is correct.

**Comment by esune** [comment]
@Jsyro yes, please remove prod if it is not used for now.

**Review by esune — APPROVED** [review]
Config looks good. I have created the new client and proof-request configuration in dev.
Happy testing, and let me know if you encounter any issues.

**Pull request merged**
